# Generated by Django 5.0.6 on 2024-06-06 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_rename_msg_chat_answer_chat_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chat',
            old_name='owner',
            new_name='question',
        ),
    ]
