# Generated by Django 5.0.6 on 2024-06-27 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0004_graph'),
    ]

    operations = [
        migrations.AddField(
            model_name='graph',
            name='question',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
